
Downloader:
  output: D
  data_directory: ./CMIP6
  model: ACCESS-ESM1-5
  experiment: ssp126
  frequency:
  variable: rsds
  realm:
  rlzn: 1
  node:
  skip:
  year:

Processor:
  to_process: 
    - ./CMIP6
  country_code: AU
  output_directory: ./Processed