
Downloader:
  output: D
  data_directory: Z:\project\ClimateAnalysis\Data
  model: ACCESS-ESM1-5
  experiment: ssp126
  frequency:
  variable: rsds
  realm:
  rlzn: 1
  node:
  skip:
  year:

Processor:
  to_process: 
    - Z:\project\ClimateAnalysis\Process
  country_code: AU
  output_directory: