
Downloader:
  output: D
  data_directory: ./CMIP6
  model: 
    - ACCESS-ESM1-5
    - UKESM1-0-LL
  experiment: ssp126
  frequency:
  variable: sfcWind
  realm:
  rlzn: 1
  node:
  skip:
  year:

Processor:
  to_process: 
    - ./CMIP6/sfcWind_Amon_ACCESS-ESM1-5_ssp126_r1i1p1f1_gn_201501-210012.nc
  country_code: AU
  output_directory: ./Test